# Generated by Django 5.0.6 on 2024-06-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="number_version",
            field=models.CharField(default=0, verbose_name="Номер версии"),
        ),
    ]
